"""fix datetime.now in model

Revision ID: 04cb77012edf
Revises: 5441d8b99410
Create Date: 2023-09-14 12:46:40.039342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cb77012edf'
down_revision = '5441d8b99410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
